config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: :show
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #

  # Products
  # delete '/products/:id', to: 'products#destroy'
  # patch '/products/:id', to: 'products#update'
  # post '/products', to: 'products#create'
  # get '/products/new', to: 'products#new', as: :new_product
  # get '/products', to: 'products#index'
  # get '/products/:id', to: 'products#show', as: :product
  # get '/products/:id/edit', to: 'products#edit', as: :edit_product
  #
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  # has_many :products, dependent: :destroy

  has_many :products, dependent: :restrict_with_exception
end

app/models/product.rb
# frozen_string_literal: true

# vendix/app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  has_one_attached :photo
  validates :title, :description, :price, presence: true

  belongs_to :category

  pg_search_scope :search_full_text, against: {
    title: 'A',
    description: 'B'
  }

  ORDER_BY = {
    newest: 'created_at DESC',
    expansive: 'price DESC',
    cheapest: 'price ASC'
  }.freeze
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController
class ApplicationController < ActionController::Base
  include Pagy::Backend

  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  private

  def locale_from_header
    request.env.fetch('HTTP_ACCEPT_LANGUAGE', '')&.scan(/[a-z]{2}/)&.first
  end
end

app/controllers/categories_controller.rb
# controller for categories
class CategoriesController < ApplicationController

  def index
    @categories = Category.all.order(name: :asc)
  end

  def new
    @category = Category.new
  end

  def edit
    category
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_url, notice: t('.create')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if category.update(category_params)
      redirect_to categories_url, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    category.destroy!
    redirect_to categories_url, notice: t('.destroyed')
  end

  private

  def category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# Products
class ProductsController < ApplicationController
  def index
    @categories = Category.order(name: :asc).load_async

    @pagy, @products = pagy_countless(FindProducts.new.call(params).load_async, items: 10)
  end

  def show
    product
  end

  def new
    @product = Product.new
    @categories = Category.all.order(name: :asc)
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: t('.create')
    else
      render :new, status: :unprocessable_entity, alert: 'Product was not created.'
    end
  end

  def edit
    product
  end

  def update
    if product.update(product_params)
      redirect_to products_path, notice: t('.update')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    product.destroy
    redirect_to products_path, notice: t('.destroy'), status: :see_other
  end

  private

  def product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :photo, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
    <%= category.name %>
    <%= link_to t('categories.edit.title'), edit_category_path(category) %>
    <%= link_to t('categories.destroy.title'), category_path(category), data: {
      turbo_method: :delete,
      turbo_confirm: t('common.confirm')
    } %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
 <% category.errors.full_messages.each do |error| %>
    <p><%= error %></p>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<div>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
  <% end %>
</div>

<%= link_to t('categories.index.new'), new_category_path %>

app/views/categories/new.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", category: @category %>

<div>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <%= render 'shared/head' %>

  <body>
    <%= render 'shared/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/products/_category.html.erb
    <div class="category">
        <li>
            <%= link_to products_path(category_id: category.id), class: 'category' do %>
                <%= category.name %>
            <% end %>
        </li>
    </div>

app/views/products/_form.html.erb
<%= form_with model: @product do |form|  %>
  <% @product.errors.full_messages.each do |error| %>
    <p><%= error %></p>
  <% end %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

    <div>
    <%= form.label :photo %><br>
    <%= form.file_field :photo %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :category %><br>
    <%= form.collection_select :category_id, @categories, :id, :name %>
  </div>

  <%= form.submit %>
<% end %>

app/views/products/_product.html.erb
<h2><%= product.title %></h2>
<p><%= product.price %></p>
<p><%= image_tag product.photo, width: 200 if product.photo.attached? %></p>
<%= link_to 'Visualziar', product_path(product.id), 'data-turbo-frame': '_top' %>

app/views/products/edit.html.erb
<%= link_to 'Voltar', products_path %>

<h2><%= t('.title') %></h2>
<hr>

<%= render 'form' %>

app/views/products/index.html.erb
<h2><%= t('.title') %></h2>
<hr>

<%= link_to t('.new'),  new_product_path %>

<%= turbo_frame_tag 'home' do %>

    <ul>
        <li> <%= link_to t('.all'), products_path %> </li>
        <%= render partial: 'category', collection: @categories %>
    </ul>

    <%= form_with url: products_path, method: :get do |form| %>
        <%= form.text_field :search_text, placeholder: t('.search_text'), onChange: 'this.form.requestSubmit()', value: params[:search_text]%><br>
        <%= form.number_field :min_price, placeholder: t('.min_price'), onChange: 'this.form.requestSubmit()', value: params[:min_price] %>
        <%= form.number_field :max_price, placeholder: t('.max_price'), onChange: 'this.form.requestSubmit()', value: params[:max_price] %><br>
        <%= form.select :order_by, options_for_select(Product::ORDER_BY.keys.map { |order| [t(".#{order}"), order]}, params[:order_by]), {}, {
            onChange: 'this.form.requestSubmit()'
        } %>
    <% end %>
    <%= turbo_frame_tag "products-#{@pagy.page}", class: 'products' do %>
        <%= render partial: 'product', collection: @products %>
        <%= turbo_frame_tag "products-#{@pagy.next}", class: 'products', src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next %>
    <% end %>
<% end %>

app/views/products/new.html.erb
<%= link_to 'Voltar', products_path %>

<h2><%= t('.title') %></h2>

<hr>

<%= render 'form' %>

app/views/products/show.html.erb
<%= link_to 'Voltar', products_path %>

<h2><%= t('.title') %></h2>

<hr>

<h2 class="title"><%= @product.title %></h2>

<h3 class="description"><%= @product.description %></h3>

<%= image_tag @product.photo, width: 200 if @product.photo.attached? %>

<p class="price"><%= @product.price %></p>


<%= link_to t('.edit'), edit_product_path(@product.id) %>

<%= link_to t('.destroy'), product_path(@product.id), data: {
    turbo_method: :delete,
    turbo_confirm: t('common.confirm')
} %>

app/views/shared/_flash_messages.html.erb
<%= alert || notice && notice["created"] || notice && notice["destroyed"] %>

app/views/shared/_head.html.erb
<head>
    <title>Vendix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>

app/views/shared/_header.html.erb
<h1>Vendix</h1>